name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 19 * * *'

# For maximum cache coherency, ensure only one outstanding build at any given time
concurrency: release

jobs:
  build:
    # Forks don't need to run the scheduled cron
    if: ${{ github.repository_owner == 'devinrsmith' || github.event_name != 'schedule' }}

    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          # "index" is shorthand for "annotation-index", https://github.com/moby/buildkit/blob/master/docs/annotations.md
          # GHCR wants it annotated an the annotation-index leevel, https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bake (release)
        uses: docker/bake-action@v6
        with:
          targets: release
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-labels }}
            cwd://${{ steps.meta.outputs.bake-file-annotations }}
        env:
          REPO_PREFIX: ghcr.io/${{ github.repository_owner }}/
